site_name: Test write-API

site_description: Documentation über den Inbound Adapter der TEST-WRITE-API
site_url: https://anhng72.github.io/test-write-api/
repo_name: liebherr/mcc_bridge_integration_weather_station
repo_url: https://github.com/AnhNg72/test-write-api

nav:
  - Home: index.md
  - Architektur:
      - Einführung und Ziele: arc42/01-introduction-and-goals.md
      - Randbedingungen: arc42/02-constraints.md
      - Kontext und Scope: arc42/03-context-and-scope.md
      - Lösungsstrategie: arc42/04-solution-strategy.md
      - Bausteinsicht: arc42/05-building-block-view.md
      - Laufzeitsicht: arc42/06-runtime-view.md
      - Verteilungssicht: arc42/07-deployment-view.md
      - Querschnittskonzepte: arc42/08-crosscutting-concepts.md
      - Architekturentscheidungen: arc42/09-architecture-decisions.md
      - Qualitätsanforderungen: arc42/10-quality-requirements.md
      - Risiken und technische Schulden: arc42/11-risks-and-technical-debt.md
  - Entwicklung und Betrieb: dev-howto.md
  - Dokumentations-Setup: docu-howto.md


theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.superfences
plugins:
  - search
  - table-reader
  - git-revision-date-localized
  - likec4:
      color_scheme: light