apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-write-api
  name: test-write-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-write-api
#  strategy: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-write-api
    spec:
      containers:
      - image: 172.29.176.1:5000/test-write-api:73384b6db39e0e90fbb8c32312581ebcdddba51e
        name: test-write-api
        imagePullPolicy: Always
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-write-api
  name: test-write-api
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-write-api
  type: ClusterIP
status:
  loadBalancer: {}
