---
name: Reusable - Deploy Docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner label"
        required: false
        type: string
        default: self-hosted

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-gh-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on:
      - ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.12"

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: npm

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --frozen --group docs
          npm ci

      - name: Build docs
        run: uv run --frozen --group docs mkdocs build --strict

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on:
      - ${{ inputs.runner }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@77d7344265e1f960dab5c00dbff52287a70b0d4f # v3